Add user data model
neckbosov/software-engineering pull request #1
Opened 2021-09-27 14:27 UTC by neckbosov

2021-09-27 19:20 UTC, jeinygroove requested changes
Спасибо за схему данных, Никита!

2021-09-27 19:20 UTC, jeinygroove commented on src/main/kotlin/dao/Achievements.kt
> +    val date = varchar("date", 20)
Мы хотим точную дату достижения знать? Может быть всё-таки года достаточно?

2021-09-27 19:20 UTC, jeinygroove commented on src/main/kotlin/dao/Achievements.kt
>      val type = varchar("type", 256)
Что такое type? Мб если типов немного то в отдельную таблицу вынести, чтобы еще юзеры могли из списка выбрать

2021-09-27 19:20 UTC, jeinygroove commented on src/main/kotlin/dao/Instructors.kt
> +object Instructors : LongIdTable() {
Professors?

2021-09-27 19:20 UTC, jeinygroove commented on src/main/kotlin/dao/Jobs.kt
> +    val fromDate = varchar("from_date", 20)
Есть ли тип даты типа только месяц и год? было бы удобней имхо

2021-09-27 19:20 UTC, jeinygroove commented on src/main/kotlin/dao/Jobs.kt
> +    val toDate = varchar("to_date", 20)
ditty

2021-09-27 19:20 UTC, jeinygroove commented on src/main/kotlin/dao/Profiles.kt
> +    val currentJobId = entityId("current_job_id", Jobs).uniqueIndex()
может быть nullable?

2021-09-27 19:20 UTC, jeinygroove commented on src/main/kotlin/dao/Students.kt
>      val faculty = varchar("faculty", 256)
что если у факультета несколько направлений, как на МКН есть математики, а есть программисты? мб заменить на специальность или направления, чтобы конкретизировать в какой области человек степень получает

2021-09-27 19:20 UTC, jeinygroove commented on src/main/kotlin/dao/Students.kt
>      val faculty = varchar("faculty", 256)
А ну и поля для ступени нет (бакалавр, магистр, пхд, и тд)

2021-09-27 21:00 UTC, neckbosov commented on src/main/kotlin/dao/Achievements.kt
> +    val date = varchar("date", 20)
там месяц и год хранится

2021-09-27 21:00 UTC, neckbosov commented on src/main/kotlin/dao/Achievements.kt
>      val type = varchar("type", 256)
ну тип это тип достижения, можно подумать над перечислением но потом мб

2021-09-27 21:01 UTC, neckbosov commented on src/main/kotlin/dao/Instructors.kt
> +object Instructors : LongIdTable() {
это к андрею, он предложил

2021-09-27 21:01 UTC, neckbosov commented on src/main/kotlin/dao/Jobs.kt
> +    val toDate = varchar("to_date", 20)
?

2021-09-27 21:01 UTC, neckbosov commented on src/main/kotlin/dao/Students.kt
>      val faculty = varchar("faculty", 256)
а нужна ли ступень если есть год обучения?

2021-09-28 05:45 UTC, jeinygroove commented on src/main/kotlin/dao/Achievements.kt
>      val type = varchar("type", 256)
ok

2021-09-28 05:46 UTC, jeinygroove commented on src/main/kotlin/dao/Jobs.kt
> +    val toDate = varchar("to_date", 20)
это значит аналогично комментарию выше, чтобы по два раза не писать

2021-09-28 05:47 UTC, jeinygroove requested changes

2021-09-28 05:47 UTC, jeinygroove commented on src/main/kotlin/dao/Profiles.kt
> +    val currentJobId = entityId("current_job_id", Jobs).uniqueIndex()
а  что из `val currentJobId = entityId("current_job_id", Jobs).uniqueIndex()` отвечает за nullable?

2021-09-28 05:47 UTC, jeinygroove commented on src/main/kotlin/dao/Students.kt
>      val faculty = varchar("faculty", 256)
5 год специалитета и 5 год бакалавриат+магистратура это разные вещи

2021-09-29 15:33 UTC, neckbosov commented on src/main/kotlin/dao/Jobs.kt
> +    val fromDate = varchar("from_date", 20)
Да, дата только месяц и год содержит

2021-09-29 15:34 UTC, neckbosov commented on src/main/kotlin/dao/Profiles.kt
> +    val currentJobId = entityId("current_job_id", Jobs).uniqueIndex()
забыл, добавлю

2021-09-29 15:35 UTC, neckbosov commented on src/main/kotlin/dao/Students.kt
>      val faculty = varchar("faculty", 256)
ок, добавлю

2021-09-29 17:11 UTC, jeinygroove requested changes

2021-09-29 17:11 UTC, jeinygroove commented on src/main/kotlin/dao/Students.kt
> +    val step = varchar("step", 50).nullable()
degree instead of step

2021-09-29 17:13 UTC, jeinygroove approved these changes

2021-09-29 17:15 UTC, merged