data models
neckbosov/software-engineering pull request #2
Opened 2021-09-27 14:37 UTC by AndreiKingsley

data models

2021-09-27 14:45 UTC, neckbosov requested changes
В целом норм, мелочи написал в коде, сейчас `dao` подгоню под это. `UserProfile` лучше поправить имхо, остальное не критично.

2021-09-27 14:45 UTC, neckbosov commented on src/main/kotlin/models/profile/UserProfile.kt
> +interface UserProfile {
Почему интерфейс если это `open class` очевидно?

2021-09-27 14:45 UTC, neckbosov commented on src/main/kotlin/models/profile/UserProfile.kt
> +interface UserProfile {
Даже точнее будет `sealed class`

2021-09-27 14:45 UTC, neckbosov commented on src/main/kotlin/models/profile/UniversityDescription.kt
> +data class UniversityDescription(
мб дучше LearningDescription?

2021-09-27 14:45 UTC, neckbosov commented on src/main/kotlin/models/profile/Status.kt
> +enum class Status {
А нужен ли отдельный `enum`? думаешь дальше будут еще статусы добавляться?

2021-09-27 14:45 UTC, neckbosov commented on src/main/kotlin/models/profile/InstructorProfile.kt
> +data class InstructorProfile(
мб все же Teacher а не Instructor?

2021-09-27 14:46 UTC, neckbosov commented on src/main/kotlin/models/profile/AchievementDescription.kt
> +    val date: String
Можно либо год оставить, либо дату прям как Date хранить

2021-09-27 14:47 UTC, AndreiKingsley commented on src/main/kotlin/models/profile/UserProfile.kt
> +interface UserProfile {
Почему это не интерфейс? Sealed class наверное норм, но мб какой-то ещё тип появиться в теории

2021-09-27 14:47 UTC, neckbosov commented on src/main/kotlin/models/profile/JobDescription.kt
> +    val period: Pair<String, String>, // TODO
Аналогично либо только годы, либо Date

2021-09-27 14:47 UTC, AndreiKingsley commented on src/main/kotlin/models/profile/UniversityDescription.kt
> +data class UniversityDescription(
Можно Education, но там инфа внутри именно университетская

2021-09-27 14:48 UTC, AndreiKingsley commented on src/main/kotlin/models/profile/Status.kt
> +enum class Status {
Будет как в ВК "всё сложно"

2021-09-27 14:49 UTC, AndreiKingsley commented on src/main/kotlin/models/profile/InstructorProfile.kt
> +data class InstructorProfile(
Ну это вроде так говорят про научрука. Он может быть не связан с тичингом

2021-09-27 14:49 UTC, neckbosov commented on src/main/kotlin/models/profile/AchievementDescription.kt
> +    val place: String,
Что такое `place`? Мб `title` имелось в виду?

2021-09-27 14:49 UTC, AndreiKingsley commented on src/main/kotlin/models/profile/AchievementDescription.kt
> +    val date: String
Я хочу пока чтобы был вид "Aug 2019"

2021-09-27 14:49 UTC, AndreiKingsley commented on src/main/kotlin/models/profile/JobDescription.kt
> +    val period: Pair<String, String>, // TODO
same

2021-09-27 14:50 UTC, AndreiKingsley commented on src/main/kotlin/models/profile/AchievementDescription.kt
> +    val place: String,
хз, чё там имелось в виду)) Ну соглы, нейминг сменить можно

2021-09-27 14:52 UTC, neckbosov commented on src/main/kotlin/models/profile/UserProfile.kt
> +interface UserProfile {
Ну у тебя общие данные а не методы, интерфейс для методов все же. Если появится новый тип отнаследуем, какие проблемы.

2021-09-27 14:52 UTC, neckbosov commented on src/main/kotlin/models/profile/UniversityDescription.kt
> +data class UniversityDescription(
ну ок, сойдет наверное

2021-09-27 14:55 UTC, neckbosov commented on src/main/kotlin/models/profile/InstructorProfile.kt
> +data class InstructorProfile(
ок

2021-09-27 14:55 UTC, neckbosov commented on src/main/kotlin/models/profile/AchievementDescription.kt
> +    val date: String
ну ок.

2021-09-27 14:56 UTC, AndreiKingsley commented on src/main/kotlin/models/profile/UserProfile.kt
> +interface UserProfile {
Ок, сделаю sealed

2021-09-27 14:57 UTC, AndreiKingsley commented on src/main/kotlin/models/profile/InstructorProfile.kt
> +    override val patronymic: String,
я специально пока что убрал  nullable (мне лень чекать как работает сериалайзер в ktor-е)

2021-09-27 14:59 UTC, neckbosov commented on src/main/kotlin/models/profile/AchievementDescription.kt
> +    val place: String,
или это имелось в виду subject...

2021-09-27 15:02 UTC, neckbosov commented on src/main/kotlin/models/profile/AchievementDescription.kt
> +    val place: String,
еще кстати стоит тип достижения добавить, короче имхо надо type, name/title и description

2021-09-27 17:19 UTC, neckbosov commented on src/main/kotlin/models/profile/UniversityDescription.kt
> +data class UniversityDescription(
Мб стоит вообще эти поля в студента перекинуть?

2021-09-27 17:19 UTC, neckbosov commented on src/main/kotlin/models/profile/UniversityDescription.kt
> +data class UniversityDescription(
и нам точно здесь нужен период?

2021-09-29 15:32 UTC, neckbosov approved these changes
Кажется все ок.

2021-09-29 15:35 UTC, merged