Server/oauth
neckbosov/software-engineering pull request #4
Opened 2021-09-29 00:09 UTC by vsalavatov

Contact me for `.secrets/google-app-desktop.txt` file (oauth client credentials)

2021-09-29 15:44 UTC, neckbosov requested changes
Мне кажется если заюзать ktorовский клиент код проще станет

2021-09-29 15:44 UTC, neckbosov commented on build.gradle.kts
> +    implementation("org.http4k:http4k-core")
А что не ktor-client?

2021-09-29 15:44 UTC, neckbosov commented on build.gradle.kts
> +    implementation("org.http4k:http4k-core")
там и автоматическая сериализация есть

2021-09-29 19:09 UTC, vsalavatov commented on build.gradle.kts
> +    implementation("org.http4k:http4k-core")
я не нашел сходу пример как сделать кастомный сервер из кейтора (не пользуясь там вот этими какими-то файлами конфигурации, какими-то application, там чет думать надо), решил попроще написать. скинь линк на пример, если найдешь, я перепишу

2021-09-30 08:04 UTC, vsalavatov commented
Пока у нас тонкий клиент, можно оставить http4k, потому что иначе придется мучиться с прокидыванием хуков из кейтора в компоуз

2021-09-30 08:10 UTC, neckbosov approved these changes

2021-09-30 08:11 UTC, jeinygroove approved these changes

2021-09-30 08:12 UTC, merged